export const SET_PRODUCTS="SET_PRODUCTS";
export const SET_SELECTED_PRODUCTS="SET_SELECTED_PRODUCTS";

export const REGISTER_START="REGISTER_START";
export const REGISTER_SUCCESS="REGISTER_SUCCESS";
export const REGISTER_FAIL="REGISTER_FAIL";

export const LOGIN_START="LOGIN_START";
export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const LOGIN_FAIL="LOGIN_FAIL";

export const SET_USER="SET_USER";

export const LOGOUT_START="LOGOUT_START";
export const LOGOUT_SUCCESS="LOGOUT_SUCCESS";
export const LOGOUT_FAIL="LOGOUT_FAIL";

export const ADD_CART ="ADD_CART";
export const REMOVE_CART="REMOVE_CART";

export const ADD_PRODUCT= "ADD_PRODUCT";
export const GET_PRODUCTS="GET_PRODUCTS";
export const GET_SINGLEPRODUCT="GET_SINGLEPRODUCT";


export const GET_CATEGORY= "GET_CATEGORY";

export const GET_CATEGORYPRODUCT= "GET_CATEGORYPRODUCT";

